# src/CHARLY/PlatformBundle/Ressources/config/services.yml
#
#    charly_platform.example:
#        class: CHARLY\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
  charly_platform.antispam:
    class: CHARLY\PlatformBundle\Antispam\Antispam
    arguments:
      - 50

  charly_platform.purger.advert:
    class: CHARLY\PlatformBundle\Purger\AdvertPurger
    arguments:
      - "@mailer"
      - "@doctrine.orm.entity_manager"

  charly_platform.email.application_mailer:
    class: CHARLY\PlatformBundle\Email\ApplicationMailer
    arguments:
      - "@mailer"
      - "charly.learn@gmail.com"

  charly_platform.doctrine_listener.application_creation:
    class: CHARLY\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@charly_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }