#    charly_platform.example:
#        class: CHARLY\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
  charly_platform.email.application_mailer:
    class: CHARLY\PlatformBundle\Email\ApplicationMailer
    arguments:
      - "@mailer"

  charly_platform.doctrine_listener.application_creation:
    class: CHARLY\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@charly_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }