# src/CHARLY/NewsBundle/Ressources/config/routing.yml
charly_news_homepage:
    path:     /
    defaults:
        _controller: CHARLYNewsBundle:News:index
charly_news_view:
    path: /{id}/{article}
    defaults:
        _controller: CHARLYNewsBundle:News:view
    requirements:
        id: \d+
        article: \d+