services:
#    charly_news.example:
#        class: CHARLY\NewsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    charly_news.fluxRss:
      class: CHARLY\NewsBundle\Controller\fluxRss
      arguments:
        - ['https://web.developpez.com/index/rss', 'https://www.alsacreations.com/rss/actualites.xml']
          #, 'https://www.it-connect.fr/feed/']
#todo ne veux pas prendre en charge la connexion avec le flux RSS https://www.it-connect.fr/feed/ limite de loading dépasser voir avec les réglages php.ini temps d'attente avant de declancher une error throw

#Si fonctionne pas dans app/service.yml
    #Tester
parameters:
    app_webmaster: "tognol charles"